### ISSUE TITLE
Viper IDE refactoring: Version checking / updating

### ISSUE THREAD

**Issue by WissenIstNacht** [viperproject/viper-ide#114]
This issue pertains to the ongoing refactoring process #113.

Viper IDE used to check and update the verisons of tools (e.g. JRE, ViperServer, etc.) used by the extension. With the current refactoring of Viper IDE, the responsible code will be removed. It should therefore be reimplemented in the refactored version of this codebase. 

Some of the relevant pieces of code that implement this functionality are:

https://github.com/viperproject/viper-ide/blob/4a493647e1cd62eaa14b016965d5c0e9cd501582/server/src/Settings.ts#L275

https://github.com/viperproject/viper-ide/blob/4a493647e1cd62eaa14b016965d5c0e9cd501582/server/src/ServerClass.ts#L376

We want to propose two possible approaches to this refactoring step:

1. Translate this functionality to Scala and implemented as part of ViperServer's LSP frontend. While this is more in line with the idea of the client/language server task repartition, it comes with some drawbacks. For example, it might lead to a situation where and outdated version of ViperServer needs to be started to update itself. 

2. Implement this in (the client side) of Viper IDE. In this approach, the tools could be checked and updated immediately on extension start, before any tool is actually used. It would also make it possible to reuse the code that currently implements these features.

**Comment by ArquintL** [comment]
`vs-verification-toolbox` (at least partially) provides such functionality for clients: [Dependency Installation](https://github.com/viperproject/vs-verification-toolbox#dependency-installation)
