### ISSUE TITLE
Verification gets stuck if the viper code cannot be parsed.

### ISSUE THREAD

**Issue by zgrannan** [viperproject/viper-ide#118]
Not sure if this is quirk of my setup or not, but here's the issue I've been seeing:

If I have buffer in vscode with the following content:
```method sum(n: Int) returns (res: Int)```.
verification works as expected.

However, if I remove a parenthesis to cause a syntax error:

```method sum(n: Int) returns (res: Int```

verification gets stuck at 99% in vscode, and I need to restart vscode to get it unstuck.

Running the server component separately, I see the error:

```
### As exception has occurred while constructing Viper AST: java.util.concurrent.ExecutionException: viper.server.core.AstConstructionFailureException$
```

Any ideas?

**Comment by aterga** [comment]
Thanks for reporting this. We will soon release a new version of Viper IDE with many fixes. In the meantime, feel free to use a more recent version, e.g. 2.2.3 (which you can install via the VS Code marketplace).

**Comment by ArquintL** [comment]
I'm closing this for now as it should be fixed since quite some time
