### ISSUE TITLE
Consider defaulting "preferences.autoSave" to false

### ISSUE THREAD

**Issue by xoudini** [viperproject/viper-ide#119]
With some configurations the auto-save completely breaks the workflow, making it nearly impossible to work on a vpr file. E.g. my VS Code configuration removes trailing whitespace and final newlines on save, which makes the cursor jump around all the time when auto-save is enabled (and especially when it [happens every second][1]).

I'm not too familiar with developing VS Code extensions, so I don't know whether it's possible to just honor the user's global/workspace auto-save preference, but that would probably be ideal.

The lack of documentation (the wiki links are dead, and the GitHub wiki is quite slim) makes it a bit of a hunt to figure out why the main preference doesn't seem to work, so to minimise frustration I'd propose disabling auto-save by default. Alternatively, the (currently 404) [wiki on this topic][2] could be published somewhere — I'm guessing this would explain the available keys and their effects.

This appears to be where auto-save is enabled by default:
https://github.com/viperproject/viper-ide/blob/4a493647e1cd62eaa14b016965d5c0e9cd501582/client/package.json#L363-L378

[1]: https://github.com/viperproject/viper-ide/blob/4a493647e1cd62eaa14b016965d5c0e9cd501582/client/src/extension.ts#L127
[2]: https://bitbucket.org/viperproject/viper-ide/wiki/Settings:%20Preferences

**Comment by ArquintL** [comment]
@xoudini Thanks for pointing out that the Wiki is incomplete. I've now migrated the remaining parts and you can find the relevant section on the `autoSave` flag [here](https://github.com/viperproject/viper-ide/wiki/Settings:-Preferences).
We do not have any plans to change this flag or its default value right now but we'll keep it in mind

**Comment by xoudini** [comment]
Thanks! Feel free to close the issue if it's a "wontfix" 🙂

**Comment by aterga** [comment]
Thanks for pointing out that the Wiki was lacking. 

We want to keep autosave for now because most users seem to benefit from having interactive verification sessions. This might change in mid-to-distant future if we start working with ASTs directly rather than writing each change to disk. 

To help switching between interactive/manual verification, Viper IDE has a special command in the command palette called 
```Viper: toggle automatic verification```. It's default binding is a sequence of two key-combinations, (Ctrl+K, Ctrl+A) or (⌘K, ⌘A) on Mac.

**Comment by xoudini** [comment]
Thanks for the response!

I'm not sure if my original sentiment was misunderstood, but to clarify: I'm not opposed to the verification triggering on saving the file. The issue I had was that my cursor was jumping all over the place due to the very frequent auto-save, since my preferred configuration strips trailing white space and newlines.

So, it was pretty much impossible to write anything since my attempt at writing e.g.
```
method foo(x: Int): returns (res: Int)
  requires 0 < x
{
...
```
...would be interrupted every second, throwing the cursor around, turning the file into something like `methodfo(ox: Int)re:turns(res:I`, before I began wondering why my VS Code configuration (which clearly had auto-save turned off) was misbehaving.

> most users seem to benefit from having interactive verification sessions. 

My suggestion here would be to let the user choose to use auto-save in their global/workspace configuration in that case, since [VS Code does in fact support auto-saving on its own][1]. The ones who don't use auto-save (so probably everyone used to running linters/formatters on saving), wouldn't have the same confusing experience I had initially.

If there's some particular reason for running the auto-saving from within the extension, the ideal solution would be to read the user's setting for the `"files.autoSave"` key, and honor that. But this would probably run the auto-save from both VS Code as well as from the extension, so maybe I just don't understand what the extension is trying to achieve with the auto-save feature.


[1]: https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save
