### ISSUE TITLE
Use the same Nailgun server for all back ends

### ISSUE THREAD

**Issue by viper-admin** [viperproject/viper-ide#15]
> Created by **@aterga** on 2016-07-06 23:41
> Last updated on 2017-03-05 13:41

Seems like there is nothing that prevents us from using a single instance of NG server running for all backends. We just need to concatenate all jars from all backends and pass them as a value for the ```-cp``` option. This will significantly reduce the delay caused by switching the backends. 

The seconds step will be to have different commands for different back ends, preferably specifying the key combination for them through the user settings json file.

**Comment by aterga** [comment]
We no longer use Nailgun
