### ISSUE TITLE
Old Viper settings detected

### ISSUE THREAD

**Issue by fpoli** [viperproject/viper-ide#211]
I tried to configure Viper to use a local Viper build, following [the link](https://github.com/viperproject/viper-ide/wiki/Settings:-Paths) suggested in the settings of the IDE. So, I wrote
```
    "viperSettings.viperServerSettings": {
        "v": "674a514867b1",
        "disableCaching": true
    },
    "viperSettings.javaSettings": {
        "v": "674a514867b1",
        "customArguments": "-Xmx2048m -Xss16m -cp $backendPaths$ -server $mainMethod$"
    },
    "viperSettings.buildVersion": "Local",
    "viperSettings.paths": {
        "v": "664a574862b1",
        "viperToolsPath": {
            "linux": "/home/fpoli/src/viperproject/viper_tools"
        },
        "z3Executable": {
            "linux": "$viperTools$/z3/bin/z3"
        },
        "boogieExecutable": {
            "linux": "$viperTools$/boogie/Binaries/Boogie.exe"
        }
    }
```
After this, the extension gives me a cryptic error: "Settings Error: Old viper settings detected: (paths) please replace the old settings with the new default settings.". Am I doing something wrong?

From the log:
```
Server: Configuration changed
ERROR: Settings Error: Old viper settings detected: (paths) please replace the old settings with the new default settings.
1 Error detected.
Server: ViperServer has stopped with exit code 0.
```

**Comment by ArquintL** [comment]
This admittedly cryptic error should indicate that the version field `v` is outdated. Could you please try to set it to `674a514867b1` (the current value found [here](https://github.com/viperproject/viper-ide/blob/a54b2ad37006b3d1e0e7f9af1c235443fb345fcb/client/package.json#L362))

**Comment by fpoli** [comment]
I see, thanks! I didn't notice that my settings use different version. They share an unusually large number of digits (`6_4a5_486_b1`) :rofl:

**Comment by fpoli** [comment]
Fixing the version the error disappears

**Comment by ArquintL** [comment]
You did not notice it because I've just updated the Wiki. The version on the Wiki page was outdated
