### ISSUE TITLE
Switching to carbon gives wrong results

### ISSUE THREAD

**Issue by totoyoyo** [viperproject/viper-ide#326]
Sometimes switching from silicon to carbon yields 1 result, and then rerunning with carbon gives a different result.

To reproduce the issue:
1. Renaming the attached file extension to `.vpr`
2. Start VSCode and open the attached file
3. Verify it with silicon, should fail with 7 errors
4. Change the backend to carbon, now the verification fails with 3 errors
5. Rerun the verification (by adding a whitespace), now the carbon verifying fails with 7 errors, different from last time.

[improper_triggers.txt](https://github.com/viperproject/viper-ide/files/9793641/improper_triggers.txt)

**Comment by ArquintL** [comment]
@totoyoyo Thanks for reporting this issue! The issue was that some verification errors were not shown for Carbon's first verification. The fix already made it into the latest nightly release, so please update the Viper Tools from within Viper-IDE
