### ISSUE TITLE
Viper on macOS arm64

### ISSUE THREAD

**Issue by fpoli** [viperproject/viper-ide#327]
I think that the Viper IDE cannot work on macOS with an arm64 chip (M1) because the Viper releases currently ships the `x64` version of Z3. We could consider releasing a `ViperToolsMac-arm64.zip` that uses e.g. [`z3-4.11.2-arm64-osx-11.0.zip`](https://github.com/Z3Prover/z3/releases/download/z3-4.11.2/z3-4.11.2-arm64-osx-11.0.zip). However, the arm64 build of Z3 is only available for recent Z3 versions.

**Comment by fpoli** [comment]
We got reports saying that the `x86_64` version of `z3` works fine, but it's not clear if it's slower than one compiled for `arm64`. If someone can evaluate this (comparing the same `z3` version compiled for different architectures) it would be great.

**Comment by ArquintL** [comment]
This is the z3 binary compiled on an ARM MacBook Pro (actually M2 but that shouldn't matter):
[z3_4.8.6_macOS_arm.zip](https://github.com/viperproject/viper-ide/files/10103711/z3_4.8.6_macOS_arm.zip)

**Comment by fpoli** [comment]
What allows to run x86 binaries on macOS arm64 is called [Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)), a dynamic binary translator. As expected, some [benchmarks](https://www.anandtech.com/show/16252/mac-mini-apple-m1-tested/6) show that it's worse than directly running a native arm64 binary.

**Comment by ArquintL** [comment]
Very interesting, thanks for sharing!

**Comment by JonasAlaif** [comment]
Fixed by my latest changes, the prebuilt `z3-arm64` lives [here](https://github.com/viperproject/boogie-builder/blob/master/prebuilt_z3/z3-4.8.7-arm64-osx.zip) and that same repo also builds `Boogie` for arm64

**Comment by fpoli** [comment]
Does the Viper IDE detect the architecture in order to download `ViperToolsMacARM.zip`  instead of `ViperToolsMac.zip`?

**Comment by fpoli** [comment]
Oh, I just noticed the latest commits. Nice!
