### ISSUE TITLE
Infinite save-as loop for Viper files that have not been saved

### ISSUE THREAD

**Issue by fpoli** [viperproject/viper-ide#366]
If I create a new file in VSCode and I write or paste some Viper code, the Viper IDE will ask every second to save the file somewhere, even when I don't want to save nor verify the file. This is annoying :-)

**Comment by fpoli** [comment]
If I surrend and choose to store the new file somewhere, then VSCode closes the file immediately after.

**Comment by fpoli** [comment]
Killing the IDE doesn't help, because VSCode restores the last session *including the files that have not been saved*. So, the infinite save-as popup loop will happen again.

**Comment by ArquintL** [comment]
Setting [`autoSave`](https://github.com/viperproject/viper-ide/wiki/Settings:-Preferences) to `false` should fix this issue. I'll remove this functionality as VSCode has the same functionality [built-in](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save).
