### ISSUE TITLE
Problems identifying the correct Program files directory

### ISSUE THREAD

**Issue by viper-admin** [viperproject/viper-ide#38]
> Created by **@aterga** on 2016-09-27 08:05
> Last updated on 2017-03-05 13:22

* OS: Windows 10 64 bit
* Version: 0.2.15

This issue also happened with the previous version of the extension, so I'm not sure that it is still there. However, filing a bug so that we don't forget about it in case it's still there. 

In the console, ```echo %ProgramFiles%``` outputs ```C:\Program files```, but the extension only finds the Viper command line tools if they are put in ```C:\Program files (x86)```. 

The installation of VS Code is also under the prefix ```C:\Program files (x86)```, but that shouldn't matter, right?

**Comment by aterga** [comment]
We no longer store files in Program files on Windows (rather in %appdata%)
