### ISSUE TITLE
Fix syntax highlighting

### ISSUE THREAD

**Issue by viper-admin** [viperproject/viper-ide#67]
> Created by **@aterga** on 2016-11-18 17:24
> Last updated on 2017-03-12 11:28

Request from Peter:

I am using the Viper Dark mode. At least there, I do not get syntax highlighting for "Set" and "union". Also, the gray for comments is too dark; could you please make it a bit brighter? Are the styles distributed together with the plugin?

And null, false, true.
It would be great to highlight "assume false".

**Comment by aterga** [comment]
Most issues mentioned here are already resolved. The ones marked ```Might be difficult; low priority``` are currently "wont fixes."
