### ISSUE TITLE
Abort of first verification after the viper tools update can lead to internal error

### ISSUE THREAD

**Issue by viper-admin** [viperproject/viper-ide#84]
> Created by bitbucket user **rukaelin** on 2017-03-20 13:17
> Last updated on 2017-03-28 13:29

Aborting the first verification after the viper tools update can lead to an internal error given unfortunate timing.

This problem can provoke 3 different internal errors from silicon and carbon:
silicon:

1. Interaction with Z3 (instance 00) failed: Unexpected output of Z3. Expected 'success' but found: (error "line 41 column 62: sort already defined $Snap") (<no position>) at viper.silicon.decider.Z3ProverStdIO.readSuccess(Z3ProverStdIO.scala:315)
2. A nullpointer exception: at viper.silicon.decider.Z3ProverStdIO.stop(Z3ProverStdIO.scala:97)
3. java.io.IOException: Stream closed at java.io.BufferedReader.ensureOpen(BufferedReader.java:122)

errors 1 and 2 also happened for carbon.

On mac the problem does not occur.

**Comment by ArquintL** [comment]
There is also a corresponding testcase in the unit tests
