### ISSUE TITLE
Aborting verification doesn't work sometimes

### ISSUE THREAD

**Issue by viper-admin** [viperproject/viper-ide#86]
> Created by **@aterga** on 2017-03-25 18:45
> Last updated on 2017-03-30 08:36

* Version: 0.5.442
* OS: macOS

Running either Carbon or Silicon on big examples. Pushing the stop button does not result in termination of the Z3 processes within more than 20 seconds. The IDE just reports "aborting" in the status bar. This did not happen before, I think it might be a recently emerged problem.

**Comment by rayman2000** [comment]
Similar issue now tracked in #417
