### ISSUE TITLE
Z3 doesn't work on old Macs

### ISSUE THREAD

**Issue by viper-admin** [viperproject/viper-ide#89]
> Created by **@aterga** on 2017-05-05 10:14

Context: shipping a binary executable for Z3 for the Mac. 

We should decide how to detect if Z3 doesn't work because of hardware limitations on old Macs. Alternatively, we could compile Z3 with legacy support. 

The feedback below is from Nils, Malte's student: 

> As I mentioned this morning I had some problems with the z3 binary
provided on the viper website. I just downloaded the binary again
from http://viper.ethz.ch/downloads/ViperToolsMac.zip to make sure the
problem still exists in the newest version, and it does. The exact
exception I’m getting is "EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP,
subcode=0x0)” at address 0x100008be8 of the binary (the first
instruction after the "z3`_GLOBAL__sub_I_main.cpp” label). The
instruction at that point is vxorps, which seems to be used to zero-out
a vector during initialization. According to Intel’s documentation this
instruction requires the AVX extension wich my CPU (Intel Core i7-860)
does not support. After downloading z3 from GitHub and compiling it
myself, everything seems to be working fine now. I’m running macOS
10.12.4 (16E195) and I’m using Visual Studio Code version 1.11.2 with
the “Viper Advanced” plugin (0.5.422), although I have the same problem
when running z3 directly from the command line.

**Comment by ArquintL** [comment]
Viper-IDE now checks whether Z3, Boogie, and Java can be found & executed. This however does not address the issue mentioned here. Since no further reports of similar problems came to my attention, I'm closing the issue for now
