### ISSUE TITLE
Viper dependencies can't be updated unless a Viper file has been opened

### ISSUE THREAD

**Issue by viper-admin** [viperproject/viper-ide#92]
> Created by **@alexanderjsummers** on 2017-08-18 15:24
> Last updated on 2017-09-19 15:29

If one opens a fresh IDE and goes to the command palette, the command to update the backend tools is suggested, but it results in a "command not found" error.

**Comment by rayman2000** [comment]
No longer necessary as we package the dependencies with the extension.
