### ISSUE TITLE
Avoid caching results across changes to back-ends

### ISSUE THREAD

**Issue by viper-admin** [viperproject/viper-ide#98]
> Created by **@alexanderjsummers** on 2018-09-14 09:53

Running an example with Silicon, and then switching the same example to Carbon causes the identical (cached) errors to be reported. This is confusing, since actually running the tool will produce a different results. The cached information should be back-[Link Text](Link URL)end-specific. For example, running the following example in Carbon and the switching to Silicon will (temporarily) produce two verification errors down the same path, even though Silicon cannot yet do this.

```
#!scala
method m(x:Int) {
    assert x > 0 
    //:: MissingOutput(assert.failed:assertion.false, /silicon/issue/34/)
    assert x > 42
}

```

**Comment by ArquintL** [comment]
There is by now the `backendSpecificCache` config option that is turned on by default to use separate caches for the backends.
